# This GitHub Actions workflow is designed to automate the deployment process.
# It triggers on push events to the main branch and runs the deployment script.

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run deployment script
        run: npm run deploy

      - name: Notify deployment success
        run: echo "Deployment successful!"